=== arxflay/notes/xml/schema.dtd
<!ELEMENT Content (Request)>
<!ELEMENT Request (Header, Body, UserData*)>
<!ELEMENT Body (#PCDATA)>
<!ELEMENT Header (Type, SubType?, (Client | ClientInfo))>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT SubType (#PCDATA)>
<!ELEMENT Client (#PCDATA)>
<!ELEMENT ClientInfo (#PCDATA)>

<!ENTITY defaultBrowser "Chrome">
<!ENTITY defaultBrowser "Chrome">

<!ATTLIST Request product_name CDATA #REQUIRED>
<!ATTLIST Request product_version ENTITIES #REQUIRED>
<!ATTLIST Type version CDATA #FIXED "1">

=== arxflay/notes/xml/xml_with_ext_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Content SYSTEM "schema.dtd">
<Content>
	<Request product_name="Test" product_version="&rx;">
		<Header>
			<Type version="1">TypeA</Type>
			<SubType>Test</SubType>
			<ClientInfo><![CDATA[<tag attr="value"></tag>]]>&defaultBrowser;</ClientInfo>
		</Header>
		<Body />
	</Request>
</Content>
